[tool.poetry]
name = "icli"
version = "0.1.0"
description = "General purpose CLI"
authors = ["Isidro Lopez <islomar@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.8"
click = "^8.1.3"

[tool.poetry.dev-dependencies]
